name: Laravel1

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

   
    
    - name: Directory Permissions
      run: |
        chmod -R 755 storage bootstrap/cache
        chmod -R 644 storage/logs

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install JavaScript Dependencies 
      run: npm install

    - name: Run Laravel Tests
      run: php artisan test
